# Generated by Django 3.2 on 2021-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210203_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carcee',
            field=models.CharField(default='', max_length=50, verbose_name='carcee'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=50, verbose_name='major'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(default='', max_length=255, verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=50, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(default='', max_length=50, verbose_name='wechat'),
        ),
    ]
